### PR TITLE
Add support for the Norid (.no) registry

### PR DESCRIPTION
**Pull request by alexrsagen**
I haven't tested all of the code, only the "check domain" call which worked fine. I don't see why the rest of the code wouldn't work though.

Would be nice if you could take a quick look and see if anything stands out or wouldn't work before merging. Thanks in advance.

### CODE REVIEW

**Comment by alexrsagen** [comment]
Found some bugs that need to be fixed. Commit is on the way.

**Comment by alexrsagen** [comment]
@metaregistrar Could you have a look at my changes?

**Comment by alexrsagen** [comment]
Updating some code to use traits instead of copying a function.

**Comment by metaregistrar** [comment]
Hi Alexander,

Thanks for your contribution, i will review it asap.

**Comment by metaregistrar** [comment]
Hello Alexander,

I have merged your code to master and made a few changes (mostly in the traits) to make sure that all code inspections are green. Please test if everything still works with the master branch.

**Pull request merged**
